import type { ReportOrganization } from "@/lib/reportOrganizations";
import { getTemplateKeyForOrganization } from "@/lib/reports/pdf/assets";
import {
  buildSharedMeatDetailSection,
  buildSharedMeatSummarySection,
} from "@/lib/reports/shared/meatSections";
import type {
  ReportDocumentModel,
  ReportSection,
} from "@/lib/reports/types";

type AdminSummary = {
  total: number;
  averageConfidence: number;
  spoiledRate: number;
  uniqueInspectors: number;
  uniqueLocations: number;
  flaggedRecords: number;
};

type AdminReportRow = {
  createdAt: string;
  inspector: string;
  location: string;
  meatType: string;
  classification: string;
  confidenceScore: number;
};

export interface BuildAdminRangeReportInput {
  reportOrganization: ReportOrganization;
  reportStartDate: string;
  reportEndDate: string;
  generatedAt: string;
  generatedBy: string;
  summary: AdminSummary;
  reportRows: AdminReportRow[];
}

export function buildAdminRangeReportModel(
  input: BuildAdminRangeReportInput,
): ReportDocumentModel {
  const overview: ReportSection = {
    id: "org-overview",
    title: "Organization Overview",
    metrics: [
      { label: "Total Inspections", value: String(input.summary.total) },
      {
        label: "Average Confidence",
        value: `${input.summary.averageConfidence}%`,
      },
      {
        label: "Spoiled Rate",
        value: `${input.summary.spoiledRate}%`,
        emphasis: "warning",
      },
      {
        label: "Unique Inspectors",
        value: String(input.summary.uniqueInspectors),
      },
      {
        label: "Unique Locations",
        value: String(input.summary.uniqueLocations),
      },
      {
        label: "Records With Deviations",
        value: String(input.summary.flaggedRecords),
      },
    ],
    detailRows: [{ label: "Generated By", value: input.generatedBy }],
  };

  return {
    organization: input.reportOrganization,
    templateKey: getTemplateKeyForOrganization(input.reportOrganization),
    kind: "admin_range",
    title: "Administrative Report",
    subtitle: `Range: ${input.reportStartDate} to ${input.reportEndDate}`,
    generatedAt: input.generatedAt,
    sections: [
      overview,
      buildSharedMeatSummarySection({
        totalInspections: input.summary.total,
        averageConfidence: input.summary.averageConfidence,
        spoiledRateLabel: `${input.summary.spoiledRate}%`,
      }),
      buildSharedMeatDetailSection({
        title: "Inspection Detail",
        columns: [
          "Created",
          "Inspector",
          "Location",
          "Meat",
          "Classification",
          "Confidence",
        ],
        rows: input.reportRows.map((row) => [
          row.createdAt,
          row.inspector,
          row.location,
          row.meatType,
          row.classification,
          `${row.confidenceScore}%`,
        ]),
      }),
    ],
  };
}
