import type { ReportOrganization } from "@/lib/reportOrganizations";
import { formatReportDateTime } from "@/lib/reports/formatting";
import { getTemplateKeyForOrganization } from "@/lib/reports/pdf/assets";
import {
  buildSharedMeatDetailSection,
  buildSharedMeatSummarySection,
} from "@/lib/reports/shared/meatSections";
import type {
  ReportChart,
  ReportDocumentModel,
  ReportInspectionEvidenceItem,
  ReportSection,
} from "@/lib/reports/types";

type AdminSummary = {
  total: number;
  averageConfidence: number;
  spoiledRate: number;
  uniqueInspectors: number;
  uniqueLocations: number;
  flaggedRecords: number;
};

type AdminReportRow = {
  createdAt: string;
  capturedAt: string | null;
  inspector: string;
  location: string;
  meatType: string;
  classification: string;
  confidenceScore: number;
  imageUrl: string | null;
};

const CLASSIFICATION_ORDER = [
  "fresh",
  "not fresh",
  "acceptable",
  "warning",
  "spoiled",
] as const;

const CLASSIFICATION_COLORS: Record<string, string> = {
  fresh: "hsl(142, 71%, 45%)",
  "not fresh": "hsl(38, 92%, 50%)",
  acceptable: "hsl(48, 96%, 53%)",
  warning: "hsl(25, 95%, 53%)",
  spoiled: "hsl(0, 84%, 60%)",
};

export interface BuildAdminRangeReportInput {
  reportOrganization: ReportOrganization;
  reportStartDate: string;
  reportEndDate: string;
  generatedAt: string;
  generatedBy: string;
  summary: AdminSummary;
  reportRows: AdminReportRow[];
}

function buildClassificationChart(reportRows: AdminReportRow[]): ReportChart {
  const counts = new Map<string, number>();

  reportRows.forEach((row) => {
    counts.set(row.classification, (counts.get(row.classification) ?? 0) + 1);
  });

  return {
    id: "classification-breakdown",
    title: "Classification Breakdown",
    kind: "bar",
    emptyState: "No data for selected range",
    points: CLASSIFICATION_ORDER
      .filter((classification) => (counts.get(classification) ?? 0) > 0)
      .map((classification) => ({
        label: classification,
        value: counts.get(classification) ?? 0,
        color: CLASSIFICATION_COLORS[classification],
      })),
  };
}

function buildDailyTrendChart(reportRows: AdminReportRow[]): ReportChart {
  const counts = new Map<string, number>();

  reportRows.forEach((row) => {
    const date = row.createdAt.slice(0, 10);
    counts.set(date, (counts.get(date) ?? 0) + 1);
  });

  return {
    id: "daily-inspection-trend",
    title: "Daily Inspection Trend",
    kind: "line",
    emptyState: "No data for selected range",
    points: Array.from(counts.entries())
      .sort((left, right) => left[0].localeCompare(right[0]))
      .map(([label, value]) => ({ label, value })),
  };
}

function buildLocationTrendChart(reportRows: AdminReportRow[]): ReportChart {
  const counts = new Map<string, number>();

  reportRows.forEach((row) => {
    const rawLocation = row.location?.trim() || "";
    const locationName = rawLocation ? rawLocation.split("|")[0].trim() : "Unspecified";
    counts.set(locationName, (counts.get(locationName) ?? 0) + 1);
  });

  return {
    id: "location-breakdown",
    title: "Location Breakdown",
    kind: "bar",
    emptyState: "No data for selected range",
    points: Array.from(counts.entries())
      .sort((left, right) => right[1] - left[1] || left[0].localeCompare(right[0]))
      .map(([label, value]) => ({ label, value })),
  };
}

function buildPorkInspectionEvidence(
  reportRows: AdminReportRow[],
): ReportInspectionEvidenceItem[] {
  return reportRows
    .filter((row) => row.meatType === "pork" && !!row.imageUrl)
    .sort((left, right) =>
      (right.capturedAt ?? right.createdAt).localeCompare(left.capturedAt ?? left.createdAt),
    )
    .map((row, index) => ({
      id: `pork-evidence-${index + 1}`,
      imageUrl: row.imageUrl,
      capturedAt: formatReportDateTime(row.capturedAt ?? row.createdAt),
      meatType: row.meatType,
      classification: row.classification,
      confidenceLabel: `${row.confidenceScore}%`,
      location: row.location,
      inspectorLabel: row.inspector,
    }));
}

export function buildAdminRangeReportModel(
  input: BuildAdminRangeReportInput,
): ReportDocumentModel {
  const overview: ReportSection = {
    id: "org-overview",
    title: "Organization Overview",
    metrics: [
      { label: "Total Inspections", value: String(input.summary.total) },
      {
        label: "Average Confidence",
        value: `${input.summary.averageConfidence}%`,
      },
      {
        label: "Spoiled Rate",
        value: `${input.summary.spoiledRate}%`,
        emphasis: "warning",
      },
      {
        label: "Unique Inspectors",
        value: String(input.summary.uniqueInspectors),
      },
      {
        label: "Unique Locations",
        value: String(input.summary.uniqueLocations),
      },
      {
        label: "Records With Deviations",
        value: String(input.summary.flaggedRecords),
      },
    ],
    detailRows: [{ label: "Generated By", value: input.generatedBy }],
  };

  const graphSection: ReportSection = {
    id: "report-graphs",
    title: "Report Graphs",
    charts: [
      buildClassificationChart(input.reportRows),
      buildDailyTrendChart(input.reportRows),
      buildLocationTrendChart(input.reportRows),
    ],
  };

  const porkInspectionEvidence = buildPorkInspectionEvidence(input.reportRows);

  return {
    organization: input.reportOrganization,
    templateKey: getTemplateKeyForOrganization(input.reportOrganization),
    kind: "admin_range",
    title: "Administrative Report",
    subtitle: `Range: ${input.reportStartDate} to ${input.reportEndDate}`,
    generatedAt: input.generatedAt,
    sections: [
      overview,
      buildSharedMeatSummarySection({
        totalInspections: input.summary.total,
        averageConfidence: input.summary.averageConfidence,
        spoiledRateLabel: `${input.summary.spoiledRate}%`,
      }),
      graphSection,
      ...(porkInspectionEvidence.length > 0
        ? [
            {
              id: "pork-gallery",
              title: "Pork Inspection Evidence",
              inspectionEvidence: porkInspectionEvidence,
              evidenceLayout: "photo-first" as const,
            } satisfies ReportSection,
          ]
        : []),
      buildSharedMeatDetailSection({
        title: "Inspection Detail",
        columns: [
          "Created",
          "Inspector",
          "Location",
          "Meat",
          "Classification",
          "Confidence",
        ],
        rows: input.reportRows.map((row) => [
          row.createdAt,
          row.inspector,
          row.location,
          row.meatType,
          row.classification,
          `${row.confidenceScore}%`,
        ]),
      }),
    ],
  };
}
