export const ROUTE_PATHS = {
  landing: "/",
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  onboarding: "/onboarding",
  inspect: "/inspect",
  history: "/history",
  messages: "/messages",
  dashboard: "/dashboard",
  profile: "/profile",
  profileTutorial: "/profile/tutorial",
  profileHelp: "/profile/help",
  profileHelpScope: "/profile/help/scope",
  admin: "/admin",
  notFound: "*",
} as const;

export const ROUTE_CONTRACT_PATHS = [
  ROUTE_PATHS.landing,
  ROUTE_PATHS.login,
  ROUTE_PATHS.signup,
  ROUTE_PATHS.forgotPassword,
  ROUTE_PATHS.resetPassword,
  ROUTE_PATHS.onboarding,
  ROUTE_PATHS.inspect,
  ROUTE_PATHS.history,
  ROUTE_PATHS.messages,
  ROUTE_PATHS.profile,
  ROUTE_PATHS.profileTutorial,
  ROUTE_PATHS.profileHelp,
  ROUTE_PATHS.profileHelpScope,
  ROUTE_PATHS.admin,
] as const;
